### ISSUE TITLE
Is there any artifact in my spectrum and time-frequency results with the use of chronux? 

### ISSUE THREAD

**Issue by jadeHuang131** [jsiegle/chronux#3]
1. Why is the beta power higher than the delta power in fig 1? (I normalized the power of each frequency band by dividing the power by the power of the whole frequency range (it should be 1~125 Hz).) Any insights into why beta power might dominate would be greatly appreciated.
![fig 1](https://github.com/user-attachments/assets/e22f8fc3-a21a-4576-80e6-15774e5b96c7)
2. Why do the results of spectral analysis differ so much between three recordings, all collected successively during the awake state (fig 2)? The variations are unexpectedly large. Could this be due to experimental conditions, processing steps, or something else? Any advice or similar experiences would be helpful.
![fig 2 ](https://github.com/user-attachments/assets/9dd6d909-6aee-4da2-9e5a-e5ac1b299c02)
3. There seem to be artifacts in my time-frequency analysis results (fig 3), I’m unsure of their origin. Has anyone encountered similar issues, and could you suggest potential causes or solutions? Your help would mean a lot—thank you!
![fig 3](https://github.com/user-attachments/assets/7e4057a7-2014-4ae9-b0d7-294f62eacc39)

**Comment by jsiegle** [comment]
Hi Jade – I don't think this is the right forum to get the help you're looking for. I would recommend contacting someone at your institution who has experience in spectral analysis. Answering your questions adequately will require knowing more details of your dataset and the experimental conditions that were used.
